#!/bin/bash

# Script to manage a local Drupal dev environment,
# in case a website is deployed to a server using Drupal


DIR_CURRENT=`dirname $0`
source $DIR_CURRENT/env.sh # Get some vars

if [ ! -f $DIR_PROJECT/settings.json ]; then
	echo "File settings.json not found"
	exit 1
fi

# Initialize Drupal repository for domains
function init_drupal_repo {
	DIR_DEFAULT=$DIR_DRUPAL_REPO/default
	if [ ! -d $DIR_DEFAULT ]; then
		mkdir -p $DIR_DEFAULT
	fi
	cd $DIR_DEFAULT

	# Get Drupal tarball
	wget https://ftp.drupal.org/files/projects/drupal-$DRUPAL_VERSION.tar.gz
	tar -xzf $DIR_DRUPAL_REPO/tar.gz
	mv ./drupal-$DRUPAL_VERSION ./drupal
	echo "- Drupal in position"

	# Get modules without installing 'em in default installation
	mkdir -p ./modules
	cd ./modules
	for KEY in ${!MODULES[@]}; do
		FILE=`basename ${MODULES[${KEY}]}`
		wget ${MODULES[${KEY}]} -O $FILE
		tar -xzf $FILE
		echo "- ${KEY} in position"
	done
	cd $DIR_DEFAULT

	# Allow Drupal to...
	# Usage of colors requires echo -e, cat and heredoc syntax won't do
	echo ""
	echo "Local dev server will start, to create some files."
	echo -e "Please ${COLOR_LIGHT_BLUE}copy autogenerated login info${COLOR_NC} and then stop the server."
	echo ""
	echo "You can use this login info in all newly created test environments."
	echo ""
	echo "After stopping the server, use this bash script to create a default tarball for Drupal resets."
	echo ""
	echo "Press enter to continue"
	echo ""
	read
	cd ./drupal
	# Start server and fork
	php core/scripts/drupal quick-start standard -s &
	# Store the process ID
	SERVER_PID=$!
	trap on_ctrl_c INT # Trap ctrl-c so that we can exit nicely
	cd $DIR_DEFAULT
}

# Ctrl-c pressed
function on_ctrl_c() {
	if [ ! $SERVER_PID -eq 0 ]; then
		kill -9 $SERVER_PID
	fi
}

# Create tarball for Drupal resets
function default_tarball {
	cd $DIR_DRUPAL_REPO/default
	rm -f ./custom.tgz
	mkdir -p ./custom/{sites,themes}
	sudo cp -afr ./drupal/sites ./custom/ # To overrule permissions
	cp -afr ./drupal/themes ./custom/
	cd ./custom
	tar -czf ../custom.tgz .
	sudo rm -rf ./custom
}

# Initialize project for usage with Drupal
function init_project {
	cd $DIR_PROJECT
	sudo rm -rf drupal
	mkdir drupal
	cd drupal
	tar -xzf $DIR_DRUPAL_REPO/default/custom.tgz
}

# Completely resetted project
function activate_project {
	# Full reset of Drupal by reinstall
	sudo rm -rf $DIR_INSTALL
	cp -ar $DIR_DRUPAL_REPO/default/drupal $DIR_INSTALL

	# Put default site in position
	DIR_TARGET=$DIR_INSTALL/sites/
	sudo rm -rf $DIR_TARGET/default
	cp -ar $DIR_PROJECT/drupal/sites/default $DIR_TARGET

	# Put default theme in position
	DIR_TARGET=$DIR_INSTALL/themes
	for FILE in `find $DIR_PROJECT/drupal/themes -mindepth 1 -maxdepth 1 -type d` ; do
		DIR=`basename $FILE`
		if [ -d $DIR_TARGET/$DIR ]; then
			rm -rf $DIR_TARGET/$DIR
		fi
		cp -afr $FILE $DIR_TARGET/
	done
}

# Cookware files to Drupal
function update_project {
	DIR_STATIC=$DIR_PROJECT/www/static
	DIR_THEME=$DIR_INSTALL/themes/default

	rsync -rau \
		$DIR_STATIC/css/ $DIR_THEME/css/

	rsync -rau \
		$DIR_STATIC/images/ $DIR_THEME/images/

	rsync -rau \
		$DIR_STATIC/js/ $DIR_THEME/js/
}

function open_notes {
	kate $DIR_STUDY/*.txt
}

function run_dev_server {
	cd $DIR_INSTALL
	php core/scripts/drupal quick-start standard -s
}

press_enter() {
	cat <<EOF

Press Enter to continue

EOF
	read
	clear
}

until [ "$SELECTION" = "0" ]; do
	clear
	# Usage of colors requires echo -e, cat and heredoc syntax won't do
	echo ""
	echo -e "    	Manage local dev Drupal installation for domain ${COLOR_LIGHT_BLUE}${DIR_DOMAIN}${COLOR_NC}"
	echo ""
	echo -e "    	${COLOR_YELLOW}Fresh installation${COLOR_NC}"
	echo    "    	1  -  Init Drupal repository"
	echo    "    	2  -  Create default tarball for Drupal resets"
	echo    "    	3  -  Init project"
	echo ""
	echo -e "    	${COLOR_YELLOW}Project testing${COLOR_NC}"
	echo    "    	4  -  (Re)actvate project"
	echo    "    	5  -  Update (copy cookware project files to Drupal)"
	echo    "    	6  -  Run dev server"
	echo ""
	echo -e "    	${COLOR_YELLOW}Other${COLOR_NC}"
	echo    "    	10 -  Open notes"
	echo ""
	echo    "    	Exit: Press enter without a choice"
	echo ""
	echo -n "  Enter selection: "
	read SELECTION
	echo ""
	case $SELECTION in
		1  ) clear ; init_drupal_repo; press_enter ;;
		2  ) clear ; default_tarball; press_enter ;;
		3  ) clear ; init_project; press_enter ;;
		4  ) clear ; activate_project; press_enter ;;
		5  ) clear ; update_project; press_enter ;;
		6  ) clear ; run_dev_server; press_enter ;;
		10 ) clear ; open_notes; press_enter ;;
		*  ) exit ;;
	esac
done
